import type { PlatformMeta } from "../types";

export const fallbackPlatforms: PlatformMeta[] = [
  {
    id: "xhs",
    name_cn: "小红书",
    name_en: "XiaoHongShu",
    enabled: true,
    status: "enabled",
    release_stage: "enabled",
    region: "cn",
    platform_type: "hybrid",
    default_route: "/platforms/xhs/dashboard",
    adapter_key: "xhs",
    risk_level: "high",
    auth_modes: ["cookie", "qr_login"],
    capabilities: [],
    accent_color: "#ff2442",
    icon: "xhs",
  },
  {
    id: "douyin",
    name_cn: "抖音",
    name_en: "Douyin",
    enabled: false,
    status: "coming_soon",
    release_stage: "planned",
    region: "cn",
    platform_type: "content",
    default_route: null,
    adapter_key: null,
    risk_level: "medium",
    auth_modes: ["none"],
    capabilities: [],
    accent_color: "#111111",
    icon: "douyin",
  },
  {
    id: "kuaishou",
    name_cn: "快手",
    name_en: "Kuaishou",
    enabled: false,
    status: "coming_soon",
    release_stage: "planned",
    region: "cn",
    platform_type: "content",
    default_route: null,
    adapter_key: null,
    risk_level: "medium",
    auth_modes: ["none"],
    capabilities: [],
    accent_color: "#ff7a00",
    icon: "kuaishou",
  },
  {
    id: "bilibili",
    name_cn: "哔哩哔哩",
    name_en: "Bilibili",
    enabled: false,
    status: "coming_soon",
    release_stage: "planned",
    region: "cn",
    platform_type: "content",
    default_route: null,
    adapter_key: null,
    risk_level: "medium",
    auth_modes: ["none"],
    capabilities: [],
    accent_color: "#00a1d6",
    icon: "bilibili",
  },
  {
    id: "wechat_channels",
    name_cn: "视频号",
    name_en: "WeChat Channels",
    enabled: false,
    status: "coming_soon",
    release_stage: "planned",
    region: "cn",
    platform_type: "social",
    default_route: null,
    adapter_key: null,
    risk_level: "medium",
    auth_modes: ["none"],
    capabilities: [],
    accent_color: "#07c160",
    icon: "wechat_channels",
  },
  {
    id: "wechat_official",
    name_cn: "公众号",
    name_en: "WeChat Official",
    enabled: false,
    status: "coming_soon",
    release_stage: "planned",
    region: "cn",
    platform_type: "content",
    default_route: null,
    adapter_key: null,
    risk_level: "medium",
    auth_modes: ["none"],
    capabilities: [],
    accent_color: "#0a9b57",
    icon: "wechat_official",
  },
  {
    id: "weibo",
    name_cn: "微博",
    name_en: "Weibo",
    enabled: false,
    status: "coming_soon",
    release_stage: "planned",
    region: "cn",
    platform_type: "social",
    default_route: null,
    adapter_key: null,
    risk_level: "medium",
    auth_modes: ["none"],
    capabilities: [],
    accent_color: "#e6162d",
    icon: "weibo",
  },
  {
    id: "xianyu",
    name_cn: "闲鱼",
    name_en: "Xianyu",
    enabled: false,
    status: "coming_soon",
    release_stage: "planned",
    region: "cn",
    platform_type: "commerce",
    default_route: null,
    adapter_key: null,
    risk_level: "medium",
    auth_modes: ["none"],
    capabilities: [],
    accent_color: "#ffe100",
    icon: "xianyu",
  },
  {
    id: "taobao",
    name_cn: "淘宝",
    name_en: "Taobao",
    enabled: false,
    status: "coming_soon",
    release_stage: "planned",
    region: "cn",
    platform_type: "commerce",
    default_route: null,
    adapter_key: null,
    risk_level: "medium",
    auth_modes: ["none"],
    capabilities: [],
    accent_color: "#ff5000",
    icon: "taobao",
  }
];

export function getPlatform(id: string | undefined) {
  return fallbackPlatforms.find((platform) => platform.id === id) ?? fallbackPlatforms[0];
}
